help("modules")

"""
  __import__(info.name)
1-modules           _winapi             hmac                selectors
2-built-in          _wmi                html                selenium
PIL                 _xxinterpchannels   http                shelve
__future__          _xxsubinterpreters  idlelib             shlex
__hello__           _yaml               idna                shutil
__phello__          _zoneinfo           imaplib             signal
_abc                abc                 imghdr              site
_aix_support        aifc                importlib           six
_ast                antigravity         inspect             sketchpy
_asyncio            argparse            io                  smtplib
_bisect             array               ipaddress           sndhdr
_blake2             ast                 itertools           sniffio
_bz2                asyncio             json                socket
_cffi_backend       atexit              keyword             socketserver
_codecs             attr                lib2to3             socks
_codecs_cn          attrs               libfuturize         sockshandler
_codecs_hk          audioop             libpasteurize       sortedcontainers
_codecs_iso2022     base64              linecache           sqlite3
_codecs_jp          bdb                 locale              sre_compile
_codecs_kr          binascii            logging             sre_constants
_codecs_tw          bisect              lzma                sre_parse
_collections        builtins            mailbox             ssl
_collections_abc    bz2                 mailcap             stat
_compat_pickle      cProfile            marshal             statistics
_compression        calendar            math                string
_contextvars        certifi             mimetypes           stringprep
_csv                cffi                mmap                struct
_ctypes             cgi                 modulefinder        subprocess
_ctypes_test        cgitb               mouseinfo           sunau
_datetime           charset_normalizer  msilib              svg
_decimal            chunk               msvcrt              svgpathtools
_elementtree        click               multiprocessing     svgwrite
_functools          cmath               netrc               symtable
_hashlib            cmd                 nntplib             sys
_heapq              code                nt                  sysconfig
_imp                codecs              ntpath              tabnanny
_io                 codeop              nturl2path          tarfile
_json               collections         numbers             telnetlib
_locale             colorama            numpy               tempfile
_lsprof             colorsys            opcode              test
_lzma               compileall          openpyxl            textwrap
_markupbase         concurrent          operator            this
_md5                configparser        optparse            threading
_msi                contextlib          os                  time
_multibytecodec     contextvars         outcome             timeit
_multiprocessing    copy                pandas              tkinter
_opcode             copyreg             past                token
_operator           crypt               pathlib             tokenize
_osx_support        csv                 pdb                 tomllib
_overlapped         ctypes              pickle              tqdm
_pickle             curses              pickletools         trace
_py_abc             cv2                 pip                 traceback
_pydatetime         dataclasses         pipes               tracemalloc
_pydecimal          datetime            pkgutil             trio
_pyio               dateutil            platform            trio_websocket
_pylong             dbm                 plistlib            tty
_queue              decimal             poplib              turtle
_random             decorator           posixpath           turtledemo
_sha1               difflib             pprint              types
_sha2               dis                 profile             typing
_sha3               doctest             pstats              typing_extensions
_signal             email               pty                 tzdata
_sitebuiltins       encodings           py_compile          unicodedata
_socket             ensurepip           pyarrow             unittest
_sqlite3            enum                pyautogui           urllib
_sre                errno               pyclbr              urllib3
_ssl                et_xmlfile          pycparser           uu
_stat               exercise1           pydoc               uuid
_statistics         faulthandler        pydoc_data          venv
_string             filecmp             pyexpat             warnings
_strptime           fileinput           pygetwindow         wave
_struct             firstModule         pymsgbox            weakref
_symtable           fnmatch             pyperclip           webbrowser
_testbuffer         fractions           pyrect              wheel
_testcapi           ftplib              pyscreeze           winreg
_testclinic         functools           pytweening          winsound
_testconsole        future              pytz                wsgiref
_testimportmultiple gc                  queue               wsproto
_testinternalcapi   genericpath         quopri              xdrlib
_testmultiphase     geocoder            random              xml
_testsinglephase    geographiclib       ratelim             xmlrpc
_thread             geopy               re                  xxsubtype
_threading_local    getopt              reprlib             yaml
_tkinter            getpass             requests            zipapp
_tokenize           gettext             rlcompleter         zipfile
_tracemalloc        glob                runpy               zipimport
_typing             graphlib            sched               zlib
_uuid               gzip                scipy               zoneinfo
_warnings           h11                 secondModule
_weakref            hashlib             secrets
_weakrefset         heapq               select
"""